version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certbot-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/usr/share/nginx/html
        depends_on:
            - certbot
    
    certbot:
        build:
            context: .
            dockerfile: Dockerfile.certbot
        volumes:
            - ./public:/usr/share/nginx/html
            - ./certbot-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./init-letsencrypt.sh:/init-letsencrypt.sh
        entrypoint: "/bin/sh -c 'docker-compose run --rm certbot certonly --webroot -w /usr/share/nginx/html -d angelsolutions.net && docker-compose exec nginx nginx -s reload'"