version: '3.8'

services:
    app:
        container_name: homepage_ui
        image: homepage_ui
        build:
            context: .
            target: production
        volumes:
            - ./src:/app/src
        ports:
            - '8080:8080'
        restart: unless-stopped