services:
    app:
        container_name: angel_solutions_ui
        build: .
        ports:
            - "3010:3010"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 400M
        restart: unless-stopped