version: '3.8'

services:
    app:
        container_name: homepage_ui
        image: homepage_ui
        build:
            context: .
            target: production
        ports:
            - '80:80'
        restart: unless-stopped