# Use certbot image as base
FROM certbot/certbot

# Copy certbot nginx configuration
COPY ./certbot-nginx.conf /etc/letsencrypt/nginx/conf.d/default.conf
COPY ./init-letsencrypt.sh /etc/letsencrypt/init-letsencrypt.sh
RUN chmod +x /etc/letsencrypt/init-letsencrypt.sh