
export default [
    {
        id: 1,
        street: 'Сливница',
        price: 60,
        color: 'brown',
        house: 50,
        mortgage: 30,
        remove_mortgage: 33,
        rent: 2,
        rent_with_color: 4,
        rent_one: 10,
        rent_two: 30,
        rent_three: 90,
        rent_four: 160,
        rent_hotel: 250
    },

    {
        id: 2,
        street: 'Ген. Тотлебен',
        price: 60,
        color: 'brown',
        house: 50,
        mortgage: 30,
        remove_mortgage: 33,
        rent: 4,
        rent_with_color: 8,
        rent_one: 20,
        rent_two: 60,
        rent_three: 180,
        rent_four: 320,
        rent_hotel: 450
    },

    {
        id: 3,
        street: 'Цар Освободител',
        price: 100,
        color: 'light-blue',
        house: 50,
        mortgage: 50,
        remove_mortgage: 55,
        rent: 6,
        rent_with_color: 12,
        rent_one: 30,
        rent_two: 90,
        rent_three: 270,
        rent_four: 400,
        rent_hotel: 550
    },

    {
        id: 4,
        street: 'Княгиня Мария Луиза',
        price: 100,
        color: 'light-blue',
        house: 50,
        mortgage: 50,
        remove_mortgage: 55,
        rent: 6,
        rent_with_color: 12,
        rent_one: 30,
        rent_two: 90,
        rent_three: 270,
        rent_four: 400,
        rent_hotel: 550
    },

    {
        id: 5,
        street: 'Генерал Скобелев',
        price: 120,
        color: 'light-blue',
        house: 50,
        mortgage: 60,
        remove_mortgage: 66,
        rent: 8,
        rent_with_color: 16,
        rent_one: 40,
        rent_two: 100,
        rent_three: 300,
        rent_four: 450,
        rent_hotel: 600
    },

    {
        id: 6,
        street: 'Алабин',
        price: 140,
        color: 'pink',
        house: 100,
        mortgage: 70,
        remove_mortgage: 77,
        rent: 10,
        rent_with_color: 20,
        rent_one: 50,
        rent_two: 150,
        rent_three: 450,
        rent_four: 625,
        rent_hotel: 750
    },

    {
        id: 7,
        street: 'Екзарх Йосиф',
        price: 140,
        color: 'pink',
        house: 100,
        mortgage: 70,
        remove_mortgage: 77,
        rent: 10,
        rent_with_color: 20,
        rent_one: 50,
        rent_two: 150,
        rent_three: 450,
        rent_four: 625,
        rent_hotel: 750
    },

    {
        id: 8,
        street: 'Опълченска',
        price: 160,
        color: 'pink',
        house: 100,
        mortgage: 80,
        remove_mortgage: 88,
        rent: 12,
        rent_with_color: 24,
        rent_one: 60,
        rent_two: 180,
        rent_three: 500,
        rent_four: 700,
        rent_hotel: 900
    },

    {
        id: 9,
        street: 'Пиротска',
        price: 180,
        color: 'orange',
        house: 100,
        mortgage: 90,
        remove_mortgage: 99,
        rent: 14,
        rent_with_color: 28,
        rent_one: 70,
        rent_two: 200,
        rent_three: 550,
        rent_four: 750,
        rent_hotel: 950
    },

    {
        id: 10,
        street: 'Александър Стамболийски',
        price: 180,
        color: 'orange',
        house: 100,
        mortgage: 90,
        remove_mortgage: 99,
        rent: 14,
        rent_with_color: 28,
        rent_one: 70,
        rent_two: 200,
        rent_three: 550,
        rent_four: 750,
        rent_hotel: 950
    },

    {
        id: 11,
        street: 'Неофит Рилски',
        price: 200,
        color: 'orange',
        house: 100,
        mortgage: 100,
        remove_mortgage: 110,
        rent: 16,
        rent_with_color: 32,
        rent_one: 80,
        rent_two: 220,
        rent_three: 600,
        rent_four: 800,
        rent_hotel: 1000
    },

    {
        id: 12,
        street: 'Солунска',
        price: 220,
        color: 'red',
        house: 150,
        mortgage: 110,
        remove_mortgage: 121,
        rent: 18,
        rent_with_color: 36,
        rent_one: 90,
        rent_two: 250,
        rent_three: 700,
        rent_four: 875,
        rent_hotel: 1050
    },

    {
        id: 13,
        street: 'Петте Кьошета',
        price: 220,
        color: 'red',
        house: 150,
        mortgage: 110,
        remove_mortgage: 121,
        rent: 18,
        rent_with_color: 36,
        rent_one: 90,
        rent_two: 250,
        rent_three: 700,
        rent_four: 875,
        rent_hotel: 1050
    },

    {
        id: 14,
        street: 'Георги С. Раковски',
        price: 240,
        color: 'red',
        house: 150,
        mortgage: 120,
        remove_mortgage: 132,
        rent: 20,
        rent_with_color: 40,
        rent_one: 100,
        rent_two: 300,
        rent_three: 750,
        rent_four: 925,
        rent_hotel: 1100
    },

    {
        id: 15,
        street: 'Ген. Скобелев',
        price: 260,
        color: 'yellow',
        house: 150,
        mortgage: 130,
        remove_mortgage: 143,
        rent: 22,
        rent_with_color: 44,
        rent_one: 110,
        rent_two: 330,
        rent_three: 800,
        rent_four: 975,
        rent_hotel: 1150
    },

    {
        id: 16,
        street: 'Граф Игнатиев',
        price: 260,
        color: 'yellow',
        house: 150,
        mortgage: 130,
        remove_mortgage: 143,
        rent: 22,
        rent_with_color: 44,
        rent_one: 110,
        rent_two: 330,
        rent_three: 800,
        rent_four: 975,
        rent_hotel: 1150
    },

    {
        id: 17,
        street: 'Площад Света Неделя',
        price: 280,
        color: 'yellow',
        house: 150,
        mortgage: 140,
        remove_mortgage: 154,
        rent: 24,
        rent_with_color: 48,
        rent_one: 120,
        rent_two: 360,
        rent_three: 850,
        rent_four: 1025,
        rent_hotel: 1200
    },

    {
        id: 18,
        street: 'Лъвов Мост',
        price: 300,
        color: 'green',
        house: 200,
        mortgage: 150,
        remove_mortgage: 165,
        rent: 26,
        rent_with_color: 52,
        rent_one: 130,
        rent_two: 390,
        rent_three: 900,
        rent_four: 1100,
        rent_hotel: 1275
    },

    {
        id: 19,
        street: 'Орлов Мост',
        price: 300,
        color: 'green',
        house: 200,
        mortgage: 150,
        remove_mortgage: 165,
        rent: 26,
        rent_with_color: 52,
        rent_one: 130,
        rent_two: 390,
        rent_three: 900,
        rent_four: 1100,
        rent_hotel: 1275
    },

    {
        id: 20,
        street: 'Булевард Витоша',
        price: 320,
        color: 'green',
        house: 200,
        mortgage: 160,
        remove_mortgage: 176,
        rent: 28,
        rent_with_color: 56,
        rent_one: 150,
        rent_two: 450,
        rent_three: 1000,
        rent_four: 1200,
        rent_hotel: 1400
    },

    {
        id: 21,
        street: 'Площад Патриарх Евтимий',
        price: 350,
        color: 'dark-blue',
        house: 200,
        mortgage: 175,
        remove_mortgage: 193,
        rent: 35,
        rent_with_color: 70,
        rent_one: 175,
        rent_two: 500,
        rent_three: 1100,
        rent_four: 1300,
        rent_hotel: 1500
    },

    {
        id: 22,
        street: 'Площад Народно Събрание',
        price: 400,
        color: 'dark-blue',
        house: 200,
        mortgage: 200,
        remove_mortgage: 220,
        rent: 50,
        rent_with_color: 100,
        rent_one: 200,
        rent_two: 600,
        rent_three: 1400,
        rent_four: 1700,
        rent_hotel: 2000
    }
]