export type Link = {
    label: string;
    url: string;
};

export type LinkSection = {
    title: string;
    links: Link[];
};

export const USEFUL_LINKS: LinkSection[] = [
    {
        title: 'German Resources',
        links: [
            { label: 'Top 100 German Words',         url: 'https://www.vistawide.com/german/top_100_german_words.htm' },
            { label: 'German Reading Comprehension', url: 'https://lingua.com/german/reading/' },
        ],
    },
    {
        title: 'IMC Krems',
        links: [
            { label: 'Graduation',    url: 'https://edesktop.fh-krems.ac.at/my-studies/studienabschluss/Pages/Start.aspx' },
            { label: 'PTS',           url: 'https://edesktop.fh-krems.ac.at/my-studies/pts/SitePages/myptsdatabus.aspx?ptsid=35070' },
            { label: 'Announcements', url: 'https://edesktop.fh-krems.ac.at/my-studies/my-cohort/SitePages/Home.aspx' },
            { label: 'Courses',       url: 'https://edesktop.fh-krems.ac.at/my-studies/my-courses/SitePages/Home.aspx' },
            { label: 'Documents',     url: 'https://edesktop.fh-krems.ac.at/my-studies/my-cohort/SitePages/Confirmations.aspx' },
            { label: 'Exams',         url: 'https://edesktop.fh-krems.ac.at/my-studies/my-schedules/Pages/MyExamSchedule.aspx' },
            { label: 'Grades',        url: 'https://edesktop.fh-krems.ac.at/my-studies/my-courses/SitePages/myGrades.aspx' },
            { label: 'Schedule',      url: 'https://edesktop.fh-krems.ac.at/my-studies/my-schedules/SitePages/Home.aspx' },
            { label: 'Guidelines',    url: 'https://edesktop.fh-krems.ac.at/knowledgebase/guidelines/SitePages/Academic%20regulations.aspx#InplviewHashb65cc378-3feb-4e55-814e-0c38fb60d88f=SortField%3DDocument_x0020_type-SortDir%3DDesc-WebPartID%3D%7BD2F7A951--9451--4848--B9E1--FD67B4040171%7D' },
        ],
    },
    {
        title: 'Software Documentations',
        links: [
            { label: 'React',       url: 'https://reactjs.org/docs/lists-and-keys.html' },
            { label: 'Express',     url: 'https://expressjs.com/en/starter/installing.html' },
            { label: 'Node',        url: 'https://nodejs.org/en/docs/' },
            { label: 'Sequelize',   url: 'https://sequelize.org/v5/manual/data-types.html' },
            { label: 'Mongoose',    url: 'https://mongoosejs.com/docs/index.html' },
            { label: 'Gatsby',      url: 'https://www.gatsbyjs.com/docs/' },
            { label: 'GraphQL',     url: 'https://graphql.org/learn/' },
            { label: 'JSON Schema', url: 'https://json-schema.org/' },
            { label: 'AJV',         url: 'https://ajv.js.org/guide/why-ajv.html' },
            { label: 'Serverless',  url: 'https://www.serverless.com/framework/docs' },
            { label: 'Claudia',     url: 'https://claudiajs.com/documentation.html' },
            { label: 'Jest',        url: 'https://jestjs.io/docs/getting-started' },
            { label: 'Mongo',       url: 'https://www.mongodb.com/docs/' },
        ],
    },
    {
        title: 'Software Tutorials',
        links: [
            { label: 'MongoDB on Ubuntu',                        url: 'https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-20-04' },
            { label: 'Nginx + Let\'s Encrypt on Ubuntu',        url: 'https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04' },
            { label: 'Django + Postgres + Nginx + Gunicorn',    url: 'https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-20-04' },
            { label: 'React Security',                          url: 'https://www.appknox.com/blog/7-react-security-vulnerabilities-every-react-developer-should-know-about' },
            { label: 'Commit Semantics',                        url: 'https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716' },
            { label: 'Express Practices',                       url: 'https://dev.to/simonplend/5-best-practices-for-building-a-modern-api-with-express-2054' },
            { label: 'Node + Express + MySQL',                  url: 'https://www.bezkoder.com/node-js-rest-api-express-mysql/' },
            { label: 'Node + JWT Auth + MySQL',                 url: 'https://www.bezkoder.com/node-js-jwt-authentication-mysql/' },
            { label: 'Angular + Node + Express + MySQL',        url: 'https://www.bezkoder.com/angular-12-node-js-express-mysql/' },
            { label: 'Angular Form Validation',                 url: 'https://www.bezkoder.com/angular-12-form-validation/' },
            { label: 'React Tutorials',                         url: 'https://www.bezkoder.com/category/react/' },
            { label: 'React + Fetch',                           url: 'https://www.bezkoder.com/react-fetch-example/#more-9815' },
            { label: 'React Absolute Imports',                  url: 'https://www.bezkoder.com/absolute-import-react/#more-9684' },
            { label: 'React + Node + Express + MySQL',          url: 'https://www.bezkoder.com/react-node-express-mysql/' },
            { label: 'Node + Express + Sequelize + MySQL',      url: 'https://www.bezkoder.com/node-js-express-sequelize-mysql/' },
            { label: 'React Structure',                         url: 'https://daveceddia.com/react-project-structure/' },
            { label: 'React Practices',                         url: 'https://alite-international.com/8-best-react-practices-to-follow/' },
            { label: 'Skeleton Components',                     url: 'https://blog.openreplay.com/3-ways-to-implement-skeleton-components-in-react' },
            { label: 'Automated Testing Practices',             url: 'https://www.toptal.com/test-automation-engineer/automated-testing-best-practices' },
            { label: 'CSS',                                     url: 'https://gist.github.com/basham/2175a16ab7c60ce8e001' },
            { label: 'No Framework Web App',                    url: 'https://medium.com/@metapgmr/hex-a-no-framework-approach-to-building-modern-web-apps-e43f74190b9c' },
            { label: 'Rename Files with Python',                url: 'https://pynative.com/python-rename-file/' },
            { label: 'CSS Flexbox',                             url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/' },
        ],
    },
    {
        title: 'Other',
        links: [
            { label: 'My Company',       url: 'https://papagal.bg/eik/206890831/f25b' },
            { label: 'Atlassian Tips',   url: 'https://docs.google.com/document/d/1LFOxzaPVXdW4RpPdJss4LBMyzNkFYvBUEQ3CgumV70E/edit#heading=h.aeg8qoexp022' },
            { label: 'My Cover Letter',  url: 'https://www.canva.com/design/DAEoHgNTlzQ/LWqdjmeWlIEVydh8vZ9I6g/edit' },
            { label: 'My Resume',        url: 'https://app.otta.com/profile' },
            { label: 'Domains',          url: 'https://www.markmonitor.com/' },
            { label: 'SMS',              url: 'https://receive-smss.com/' },
            { label: 'Solidity',         url: 'https://cryptozombies.io/' },
            { label: 'Electronics Parts', url: 'https://lcsc.com/' },
        ],
    },
    {
        title: 'Temporary Links',
        links: [
            { label: 'Reshot Calendar Icons',               url: 'https://www.reshot.com/free-svg-icons/calendar/' },
            { label: 'One Time Secret',                   url: 'https://onetimesecret.com/' },
            { label: 'Online Java Compiler',              url: 'https://www.tutorialspoint.com/online_java_compiler.php' },
            { label: 'YouTube Video 1',                   url: 'https://www.youtube.com/watch?v=YysKbNk1tj0' },
            { label: 'Jira App in Docker (Atlassian SDK)', url: 'https://www.anovaapps.com/how-to-run-your-atlassian-jira-app-from-atlassian-sdk-in-docker/' },
            { label: 'Cron Expression Generator',         url: 'https://www.freeformatter.com/cron-expression-generator-quartz.html' },
            { label: 'Desmos Calculator',                 url: 'https://www.desmos.com/calculator/zs5wfg9uem' },
            { label: 'useState Multiple Calls (SO)',      url: 'https://stackoverflow.com/questions/53574614/multiple-calls-to-state-updater-from-usestate-in-component-causes-multiple-re-re' },
            { label: 'YouTube Video 2',                   url: 'https://www.youtube.com/watch?v=lkIFF4maKMU' },
            { label: 'YouTube Video 3',                   url: 'https://www.youtube.com/watch?v=erEgovG9WBs' },
            { label: 'Zodiac Killer Letters',             url: 'https://www.zodiackiller.com/Letters.html' },
            { label: "Men's Track & Field World Records", url: 'https://trackandfieldnews.com/records/mens-world-records/' },
            { label: 'World Athletics Records',           url: 'https://www.worldathletics.org/records/by-category/world-records' },
            { label: 'Squatwolf',                         url: 'https://squatwolf.com/en-bg' },
            { label: 'Deadlift Strength Standards',       url: 'https://strengthlevel.com/strength-standards/deadlift/kg' },
            { label: 'Pace Conversion Chart',             url: 'https://www.depicus.com/swim-bike-run/pace-conversion-chart' },
            { label: 'Wojak Paradise',                    url: 'https://wojakparadise.net/' },
            { label: "Burke's Peerage",                   url: 'https://www.burkespeerage.com/home.php' },
            { label: 'Dermaroller 540 Titanium (eMAG)',   url: 'https://www.emag.bg/ured-za-vyzstanovjavane-na-kozhata-rahelr-dermaroller-efikasen-pri-belezi-strii-540-igli-ot-titan-1-50-m-bg0013/pd/D1Y2NSBBM/' },
            { label: 'Explore 500 Mountain Bike (Decathlon)', url: 'https://www.decathlon.bg/p/330628-200022_planinski-velosiped-za-prehodi-explore-500-29quote-cheren.html' },
            { label: 'Dell U2723QE 27" 4K Monitor (eMAG)', url: 'https://www.emag.bg/monitor-dell-27-ips-4k-uhd-60hz-5ms-99-srgb-color-gamut-hdmi-display-port-usb-usb-c-pivot-u2723qe/pd/DRC10JMBM/' },
            { label: 'iPad Pro 12.9 2022 6th Gen (eMAG)', url: 'https://www.emag.bg/apple-ipad-pro-12-9-2022-6th-gen-2tb-cellular-silver-mp273hc-a/pd/D129GZMBM/' },
            { label: "Captain's Crush Hand Gripper (Amazon)", url: 'https://www.amazon.com/Captains-Crush-Hand-Gripper-Guide/dp/B0002U49CS' },
            { label: 'WebSocket: Java + React (dev.to)',  url: 'https://dev.to/fpeluso/a-simple-websocket-between-java-and-react-5c98' },
            { label: 'AWS Website Hosting',               url: 'https://aws.amazon.com/websites/' },
            { label: 'Java ServerSocket (GFG)',           url: 'https://www.geeksforgeeks.org/java-net-serversocket-class-in-java/' },
            { label: 'WebSocket Client API (MDN)',        url: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications' },
            { label: 'Spring STOMP WebSocket Guide',      url: 'https://spring.io/guides/gs/messaging-stomp-websocket/' },
            { label: 'WebSockets with Spring (Baeldung)', url: 'https://www.baeldung.com/websockets-spring' },
        ],
    },
    {
        title: 'Piano Pieces',
        links: [
            { label: 'Tokyo Ghoul - Unravel',               url: 'https://www.youtube.com/watch?v=-AVWEtlG3iQ' },
            { label: 'Mozart - Rondo Alla Turca',            url: 'https://www.youtube.com/watch?v=LrRp80PrD04' },
            { label: 'Mozart - Eine Kleine Nachtmusik',      url: 'https://www.youtube.com/watch?v=etr_z9Z51QE' },
            { label: 'Queen - Killer Queen',                 url: 'https://www.youtube.com/watch?v=PBAmGHS6Yt8' },
            { label: 'Queen - Bohemian Rhapsody',            url: 'https://www.youtube.com/watch?v=a7vqHDWG8y0' },
            { label: "Queen - Don't Stop Me Now",            url: 'https://www.youtube.com/watch?v=ta4dvz3qrC4' },
            { label: 'AC/DC - Thunderstruck',                url: 'https://www.youtube.com/watch?v=lu3HST4dNyQ' },
            { label: 'Beethoven - Für Elise',                url: 'https://www.youtube.com/watch?v=WvWuco54FHg' },
            { label: 'Beethoven - Ode to Joy',               url: 'https://www.youtube.com/watch?v=VBqLrMqvWbg' },
            { label: 'Beethoven - 5th Symphony',             url: 'https://www.youtube.com/watch?v=8NH2pTj5WN0' },
            { label: 'Beethoven - Moonlight Sonata Mvt. III', url: 'https://www.youtube.com/watch?v=gO2KhJQLo-4' },
            { label: 'Offenbach - Can-Can',                  url: 'https://www.youtube.com/watch?v=W5qVWHwcf20' },
            { label: 'Khachaturian - Sabre Dance',           url: 'https://www.youtube.com/watch?v=txu7njiC2vc' },
            { label: 'Carmina Burana - O Fortuna',           url: 'https://www.youtube.com/watch?v=8Cg77i9pej8' },
            { label: 'Rossini - The Barber of Seville',      url: 'https://www.youtube.com/watch?v=-ia38zawBOQ' },
            { label: 'Bizet - Toreador Song',                url: 'https://www.youtube.com/watch?v=1uZR1mz-uvI' },
            { label: 'Henry Mancini - The Pink Panther',     url: 'https://www.youtube.com/watch?v=5SLrR9DkRe8' },
            { label: 'Felix Mendelssohn - Wedding March',    url: 'https://www.youtube.com/watch?v=rawcnSVGtfk' },
            { label: 'Who Wants to Be a Millionaire Theme',  url: 'https://www.youtube.com/watch?v=f8pgG3o-BF0' },
            { label: 'Gravity Falls Theme',                  url: 'https://www.youtube.com/watch?v=l8JspQNT5zI' },
            { label: 'Fort Boyard',                          url: 'https://www.youtube.com/clip/UgkxrYVaxkzWSp3AmNLEFDXXNu7YJ_sn3BHS' },
        ],
    },
    {
        title: 'Useful Sites',
        links: [
            { label: 'Visited Countries',    url: 'https://visitedplaces.com/world/?map=world&projection=geoEquirectangular&theme=dark-blue&width=1600&height=757&water=1&graticule=0&names=1&duration=2000&placeduration=100&slider=0&autoplay=0&autozoom=none&autostep=0&home=BG&places=~RS_HU_AT_GR_HR_SI_ME_MK_IT_ES_RO_VA' },
            { label: 'Magisto',              url: 'https://magisto.com' },
            { label: 'Subject Line',         url: 'https://subjectline.com' },
            { label: 'Google Alerts',        url: 'https://google.com/alerts' },
            { label: 'Brand Yourself',       url: 'https://brandyourself.com' },
            { label: 'Beautiful.ai',         url: 'https://beautiful.ai' },
            { label: 'Content Drips',        url: 'https://contentdrips.com' },
            { label: '123apps',              url: 'https://123apps.com' },
            { label: 'Exploding Topics',     url: 'https://explodingtopics.com' },
            { label: 'Magic Eraser',         url: 'https://magiceraser.io' },
            { label: 'CSS Neon Glow',        url: 'https://css-tricks.com/how-to-create-neon-text-with-css/' },
            { label: 'CSS Polygon Clipper',  url: 'https://bennettfeely.com/clippy/' },
            { label: 'Stock Charts',         url: 'https://www.financecharts.com/' },
            { label: 'Compound Interest',    url: 'https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator' },
            { label: 'Direct Flights',       url: 'https://www.flightconnections.com/' },
        ],
    },
];
