name: Homepage UI CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        steps:
            -   name: pull repo, build and deploy to server
                uses: appleboy/ssh-action@v1.0.3
                with:
                    debug: true
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        cd /home/ubuntu/services/homepage-ui
                        git stash push --include-untracked
                        git stash drop
                        git pull origin master