name: Homepage UI CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        steps:
            -   name: pull repo, build and deploy to server
                uses: appleboy/ssh-action@v1.0.3
                with:
                    debug: true
                    host: ${{ secrets.AS_IP }}
                    username: ${{ secrets.AS_USER }}
                    key: ${{ secrets.AS_KEY }}
                    script: |
                        cd /root/services/homepage-ui
                        docker compose down
                        git stash push --include-untracked
                        git stash drop
                        git pull origin master
                        docker compose up -d